### ISSUE TITLE
The app doesn't have its own Player

### ISSUE THREAD

**Issue by MrConqueror** [BeamlakAschalew/cinemax#18]
### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

### Android version

.

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by OshekharO** [comment]
Please follow proper guidline to open an issue. Also we know about this will try to do something.

**Comment by Harshdeepsinghh** [comment]
> 

pls add a player like cloudstream 3 I guess they are using exo player
