### ISSUE TITLE
App is good in terms of UI design 

### ISSUE THREAD

**Issue by MrConqueror** [BeamlakAschalew/cinemax#21]
### Source information

.

### Source link

.

### Steps to reproduce

Add more source 

### Android version

Android 12

### Other details

![Screenshot_2022-11-03-14-57-18-922_cf beamlakaschalew cinemax](https://user-images.githubusercontent.com/102837820/199662869-cdc581f4-48e9-4ae0-a9e0-d31657679341.jpg) all movies in this app doesn't play 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by BeamlakAschalew** [comment]
The streaming feature isn't working because 2embed.biz is inactive, i think they'll fix it

**Comment by MrConqueror** [comment]
> The streaming feature isn't working because 2embed.biz is inactive, i think they'll fix it

Please make built-in player

**Comment by BeamlakAschalew** [comment]
2embed.biz apparently changed how they display videos and the new system is kind of hard to scrape, maybe I'll use selenium for automation in the future.

**Comment by DarkCrypt** [comment]
@BeamlakAschalew 

Since you've acquired better sources and have also included an in-app video player recently, you can probably close this issue out.

**Comment by BeamlakAschalew** [comment]
> @BeamlakAschalew 
> 
> Since you've acquired better sources and have also included an in-app video player recently, you can probably close this issue out.

Yeah, I forgot to do that, thanks.
