### ISSUE TITLE
In-App Updater For v2.0.0 -> v1.4.2 Downgrade

### ISSUE THREAD

**Issue by DarkCrypt** [BeamlakAschalew/cinemax#26]
### Steps to reproduce

Go to:
1. Click the menu icon
2. Click check for an update
3. App says update is available
4. New version update is a downgrade

### Expected behavior

In-app updater status should say "No Update Available".

### Actual behavior

In-app updater status says "Update Available" but is a downgrade version.

### Android version

Android 13

### Other details

See screenshot.

![Screenshot_Cinemax_Updater](https://user-images.githubusercontent.com/121076677/236066422-ffe90453-57e6-47da-87fe-e1835773058d.jpg)

Note: v1.4.2 had no update available to v2.0.0.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by DarkCrypt** [comment]
V.2.1.0 -> no in-app update to v.2.1.1.
V.2.1.1 -> v.2.1.0 downgrade.

**Comment by BeamlakAschalew** [comment]
I forgot to update in the json. It's fixed now. Thanks
