### ISSUE TITLE
Reduce contrast

### ISSUE THREAD

**Issue by lewdpatriot** [BeamlakAschalew/cinemax#30]
### Steps to reproduce

The contrast of the ui elements is very high, specially in dark mode. Please reduce it. Also, some texts are not shown properly. Screenshot below

### Expected behavior

N/A

### Actual behavior

N/A

### Android version

Android 11

### Other details

![IMG_20230224_011309](https://user-images.githubusercontent.com/63286528/221013942-8e04bef1-f119-4427-bb08-8bc9465f8279.jpg)
![IMG_20230224_011248](https://user-images.githubusercontent.com/63286528/221013979-81197ede-a11a-47d5-b530-48bead2fbb37.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by BeamlakAschalew** [comment]
Okay, I was going twitter style with the contrast but it's too much so I will tone it down a little, but the texts not showing up on the buttons is weird, I'll fix that too, in the next fix version.

**Comment by BeamlakAschalew** [comment]
Did you have "Material 3 theming" enabled on the settings?

**Comment by lewdpatriot** [comment]
> Did you have "Material 3 theming" enabled on the settings?

No, I'm on android 11, no use enabling it😅

**Comment by BeamlakAschalew** [comment]
> > Did you have "Material 3 theming" enabled on the settings?
> 
> No, I'm on android 11, no use enabling it😅

Oh because I thought if it is enabled and your Android is below 11, the theme becomes null if it's not handled correctly and I thought maybe that was the problem.

**Comment by lewdpatriot** [comment]
I think it actually was the issue. I enabled it to see if something does happen but then disabled it, and it probably didn't revert back properly ( more headache for you) . I reinstalled and it's fine now. Thank you.

**Comment by BeamlakAschalew** [comment]
Yeah that happens, usually restarting the app will do good but I'm thinking of hiding the option for devices below Android 12, or handle all null colors, thanks for the feedback!

**Comment by BeamlakAschalew** [comment]
Contrast is lowered as of v1.4.2
