### ISSUE TITLE
...

### ISSUE THREAD

**Issue by rianaokel** [BeamlakAschalew/cinemax#44]
### Source information

New source

### Source link

Newsource.com

### Steps to reproduce

New source

### Android version

New source

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by BeamlakAschalew** [comment]
> ### Source information
> 
> New source
> 
> ### Source link
> 
> Newsource.com
> 
> ### Steps to reproduce
> 
> New source
> 
> ### Android version
> 
> New source
> 
> ### Other details
> 
> _No response_
> 
> ### Acknowledgements
> 
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> - [X] I have written a short but informative title.
> - [X] If related to a provider, I have checked the site and it works, but not the app.
> - [X] I will fill out all of the requested information in this form.

Would you mind sharing the app version you're using and a specific movie or TV series?
