### ISSUE TITLE
I can't watch anything

### ISSUE THREAD

**Issue by Fuzzythegoatq** [BeamlakAschalew/cinemax#47]
### Steps to reproduce

I'm new to cinemax, and I'm trying to watch something and it will not work. Can someone help me with this?

### Expected behavior

Idk

### Actual behavior

Idk

### Android version

Android 13

### Other details

Idk

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by BeamlakAschalew** [comment]
Can you provide the app version, and the movie/TV episode you're trying to open?

**Comment by Fuzzythegoatq** [comment]
![Screenshot_20230815_132136](https://github.com/BeamlakAschalew/cinemax/assets/124460008/fc194719-9b02-4ab9-bf13-4f1906f0e63c)

**Comment by BeamlakAschalew** [comment]
Please check discussions https://github.com/BeamlakAschalew/cinemax/discussions

**Comment by BeamlakAschalew** [comment]
> Please check discussions https://github.com/BeamlakAschalew/cinemax/discussions

More specifically the Notices tab

**Comment by BeamlakAschalew** [comment]
Checkout https://github.com/BeamlakAschalew/cinemax/releases/tag/v2.1.1-bv2 and download the APK

**Comment by Fuzzythegoatq** [comment]
> Can you provide the app version, and the movie/TV episode you're trying to open?

I'm using the latest version and it works! Thanks. I'll come back if I have any errors or problems.
