### ISSUE TITLE
Improvement Suggestions

### ISSUE THREAD

**Issue by OshekharO** [BeamlakAschalew/cinemax#5]
1. Add bottom navigation [google_nav_bar](https://pub.dev/packages/google_nav_bar)
2. Beautify Watch Now Section ( it looks ugly showing like stream 1 multi player and all ) or even if you want theme then atleast add those texts to block style.
3. Transfer watch now to watch Provider's -> free section
4. Add inbuilt player instead of webview. (Bonus if possible to reduce ads)
5. Change the theme color to amoled black: [Theme](https://www.flutterant.com/switching-themes-in-flutter-apps/) 
6. Shift to Material designe but if it looks ugly ignore this.
7. Add Watchlist Section & Notify the user when an unreleased movie in their watchlist is released
8. Add Anime Section: [Anime](https://api.gdriveplayer.us/) 
9. Browse movies by popularity, release date or genres:  [fandofastest](https://github.com/fandofastest/newmoviea1/blob/4ecc634b16cd600714f955694072ea89a1d5c6bc/app/src/main/java/com/hdmovies/fullhdmovies/ItemMovieActivity.java)
10. Edge Curvy hero slider ( trending movies)
11. For setting & about page: [Musify](https://github.com/gokadzev/Musify/)
12. Implement omdb api to fetch from IMDb: [omdbapi](https://www.omdbapi.com/)
13. It will be lot better if movies and series are displayed in grid style instead of list style when we click on genres.
14. Add subtitle option in player: [movies-src](https://movies-src.web.app/embed/38700)
15. Webview Adblocker: [Adblocker](https://github.com/BeamlakAschalew/cinemax/issues/5#issuecomment-1179562717)
16. Redesign Video Player: [vidplay](https://github.com/BeamlakAschalew/cinemax/issues/5#issuecomment-1179561793)
17. Movie Detail Page UI: [inKino](https://github.com/roughike/inKino/blob/development/assets/screenshots/event_details.png) 
18. Movie Provider Revamp: [Ref](https://github.com/BeamlakAschalew/cinemax/issues/5#issuecomment-1185128150)

@BeamlakAschalew

**Comment by OshekharO** [comment]
Also merge branch 1.3.0 into main and release latest beta build

**Comment by BeamlakAschalew** [comment]
1. I'm planning on adding dark theme switch feature and settings to enable adult preferences.
2. I will :)
3. I will :)

**Comment by BeamlakAschalew** [comment]
The code of v1.3.0 is a mess, i will use provider to refactor it.

**Comment by OshekharO** [comment]
Also you can take idea from this for bottom navigation ( https://m.sauflix.com ) and also some other features

**Comment by BeamlakAschalew** [comment]
4. I couldn't find a method to get the specific video file for a movie. Like fatherhood.mp4. that's why I'm embedding websites, do you know how to get .mp4 direct links?
5. I will :)

**Comment by BeamlakAschalew** [comment]
We'll make a video player if we get direct .mp4 or .avi links

**Comment by OshekharO** [comment]
> 4. I couldn't find a method to get the specific video file for a movie. Like fatherhood.mp4. that's why I'm embedding websites, do you know how to get .mp4 direct links?
> 5. I will :)

Mosty i use third-party streaming website's

**Comment by OshekharO** [comment]
> We'll make a video player if we get direct .mp4 or .avi links

You can extract MP4 and avi but then you will have to make extract and implement it in the app

**Comment by OshekharO** [comment]
For UI styling i think you can get ideas from here: https://github.com/yasinkacmaz/jetflix

**Comment by OshekharO** [comment]
Bottom Navigation: https://pub.dev/packages/google_nav_bar

**Comment by BeamlakAschalew** [comment]
They look great, I'll take UI designs from them

**Comment by OshekharO** [comment]
@BeamlakAschalew how about this https://www.forum.projexcode.com/2020/10/membuat-multiple-episode-post-streaming.html?m=1 instead of default iframe?

**Comment by OshekharO** [comment]
Change repo description from some app -> Android App For Streaming Movies And TV-Series.

**Comment by OshekharO** [comment]
> What is a hero slider? @OshekharO

Ah sorry it is related to web development ignore it.

I mean to say add slide show like this : 
![IMG_20220706_141412](https://user-images.githubusercontent.com/95137948/177509358-8f8ba7b0-b2ec-4269-a633-3aca738739b7.png)

**Comment by BeamlakAschalew** [comment]
The app already has a carousel slider but I'll modify it
@OshekharO

**Comment by BeamlakAschalew** [comment]
I have exams too, I'll do my coding on Saturday

**Comment by OshekharO** [comment]
👍

**Comment by OshekharO** [comment]
Also check this out: https://github.com/diaaAlterh/cinephilia/blob/bbf2b98bd9c9bae11241aedf6cb7d7a7e0f08254/lib/ui/details_screen.dart#L245

**Comment by OshekharO** [comment]
For anime: https://databasegdriveplayer.co/anime.php?id=

**Comment by OshekharO** [comment]
@BeamlakAschalew imdb api is also implemented or only tmdb?

**Comment by BeamlakAschalew** [comment]
imdb's API isn't public, I only use tmdb API. But there's API provider that has imdb's data

**Comment by OshekharO** [comment]
@BeamlakAschalew can you add option in vidplayer like drop down ( select server)

**Comment by OshekharO** [comment]
![IMG_20220709_205526](https://user-images.githubusercontent.com/95137948/178112097-367cd354-70b4-48fe-bba8-a1fd002a57e2.jpg)

Like this one.

**Comment by BeamlakAschalew** [comment]
We can do this. It's technically a bottom navigation bar

**Comment by OshekharO** [comment]
I think it's good to remove similar tab as recommendation tab is enough for that and also it's good to remove crew tab.

Also remove cast from about tab as seperate cast tab is present. Social media section & movie info is also waste.

@BeamlakAschalew

**Comment by OshekharO** [comment]
> We can do this. It's technically a bottom navigation bar

Yes that looks better and also is there any way to remove ads or atleast reduce them: https://github.com/marcelbohland/Android-Webview-Adblock ?

**Comment by BeamlakAschalew** [comment]
> I think it's good to remove similar tab as recommendation tab is enough for that and also it's good to remove crew tab.
> 
> Also remove cast from about tab as seperate cast tab is present. Social media section & movie info is also waste.
> 
> @BeamlakAschalew

Social media section is necessary, it provides users the option to navigate more about the movie or tv series, I'll remove the cast from the about section, crew tab provides nerd users with behind-the-scenes data so let it be, and let me take a look at the differences and similarity between 'recommendations' and 'similar', then if it provides the same data I'll delete it.

**Comment by BeamlakAschalew** [comment]
> > We can do this. It's technically a bottom navigation bar
> 
> Yes this looks better than list style and also is there any way to remove ads or atleast reduce them: https://github.com/marcelbohland/Android-Webview-Adblock , https://github.com/islamdidarmd/AdBlockerWebview

this looks good, I'll check it out

**Comment by BeamlakAschalew** [comment]
@OshekharO 
check this site superembed.stream

**Comment by OshekharO** [comment]
@BeamlakAschalew https://github.com/OshekharO/Link-Crawler/blob/main/apis.json here you go.

**Comment by OshekharO** [comment]
> @OshekharO check this site superembed.stream

I know this site is good and have many servers

**Comment by OshekharO** [comment]
@BeamlakAschalew bro can you add subtitle option in player like: https://movies-src.web.app/embed/38700 ?

**Comment by OshekharO** [comment]
It will be lot better if movies show in grid style instead of list style when we click on genres.

**Comment by OshekharO** [comment]
@BeamlakAschalew for setting & home page you can take design from here : https://github.com/gokadzev/Musify/tree/master/lib/ui ( also inbuilt Updater).

**Comment by OshekharO** [comment]
Also configure workflow for auto building the app

**Comment by OshekharO** [comment]
https://documenter.getpostman.com/view/18986031/UVXdNeFD

**Comment by BeamlakAschalew** [comment]
> Also configure workflow for auto building the app

What is that?

**Comment by OshekharO** [comment]
> > Also configure workflow for auto building the app
> 
> What is that?

Ignore this. It mainly uses GitHub action to build the application and release it automatically.

**Comment by OshekharO** [comment]
https://github.com/OkoloArt/Stream you can take idea from here also

**Comment by OshekharO** [comment]
@BeamlakAschalew you can take idea from here https://github.com/fandofastest/newmoviea1/blob/4ecc634b16cd600714f955694072ea89a1d5c6bc/app/src/main/java/com/hdmovies/fullhdmovies/ItemMovieActivity.java if you wish to add filter search option in the app.

**Comment by OshekharO** [comment]
I have updated all the suggestion: https://github.com/BeamlakAschalew/cinemax/issues/5#issue-1295019930

**Comment by OshekharO** [comment]
@BeamlakAschalew i think you can take idea for movie details and tv show details page ui idea from here: https://github.com/vendz/Cineapp

**Comment by OshekharO** [comment]
Also when going to release latest test build?

**Comment by OshekharO** [comment]
Make Movie Provider section like this: 
![178099450-5186eb20-ea12-4247-b172-a4021228a5af](https://user-images.githubusercontent.com/95137948/179142171-b55bfaee-3f5c-4e8f-a47e-c4991de14de9.png)

**Comment by BeamlakAschalew** [comment]
> Also when going to release latest test build?

Probably after a month

**Comment by OshekharO** [comment]
@BeamlakAschalew bro remove the Side Drawer as you have already implemented bottom navigation just move the search from top to bottom navigation.

**Comment by BeamlakAschalew** [comment]
> @BeamlakAschalew bro remove the Side Drawer as you have already implemented bottom navigation just move the search from top to bottom navigation. 
> 
> **Note**: features number 5,8,12,14,15,16 are important.

Where would the settings and about screen go to? And why do I need omdb api?

**Comment by BeamlakAschalew** [comment]
Bro send me the list of the third party movie and tv show streaming websites

**Comment by OshekharO** [comment]
> > @BeamlakAschalew bro remove the Side Drawer as you have already implemented bottom navigation just move the search from top to bottom navigation.
> > Note: features number 5,8,12,14,15,16 are important.
> 
> Where would the settings and about screen go to?

Check suggestion no: 11

**Comment by OshekharO** [comment]
> Bro send me the list of the third party movie and tv show streaming websites

Like sites which fetch from IMDb and tmdb ?? Example: 2embed or any third party sites which provides movie?

**Comment by OshekharO** [comment]
@BeamlakAschalew from here i think you will get the Idea for adding options in settings: https://play.google.com/store/apps/details?id=com.moviebase ( it's UI is also Good )

**Comment by OshekharO** [comment]
Also check if it's feasible to fetch movies from the server which this app is using: https://github.com/AnkitVats21/PremiumVerse

**Comment by BeamlakAschalew** [comment]
> > Bro send me the list of the third party movie and tv show streaming websites
> 
> Like sites which fetch from IMDb and tmdb ?? Example: 2embed or any third party sites which provides movie?

Like 2embed but sites which don't have too much ads

**Comment by OshekharO** [comment]
> > > Bro send me the list of the third party movie and tv show streaming websites
> > 
> > 
> > Like sites which fetch from IMDb and tmdb ?? Example: 2embed or any third party sites which provides movie?
> 
> Like 2embed but sites which don't have too much ads

Not possible first of all i have already added most of the site's and second all the site's like This one will have many ads.

**Comment by OshekharO** [comment]
Make about page like this: https://github.com/LawnchairLauncher/lawnchair/blob/5669d32b78e8ce5e18a239e021504ce0fc31b282/lawnchair/src/app/lawnchair/ui/preferences/about/About.kt

**Comment by BeamlakAschalew** [comment]
@OshekharO send me the list of websites that provide API for movie streaming you once sent me, i think it was someone's repository

**Comment by OshekharO** [comment]
@BeamlakAschalew https://github.com/OshekharO/Link-Crawler

**Comment by RowdyRogue** [comment]
Can we have download section ,the app looks soo good so I switched from cloudstream to this but It doesn't have downloads Option like cloudstream

**Comment by BeamlakAschalew** [comment]
> Can we have download section ,the app looks soo good so I switched from cloudstream to this but It doesn't have downloads Option like cloudstream

@RowdyRogue Thank you for the feedback! I'm currently exploring options to get direct stream links in .mp4 or .m3u8 format, once I get a reliable source we'll ditch webview and downloading option will be available.

**Comment by RowdyRogue** [comment]
> > Can we have download section ,the app looks soo good so I switched from cloudstream to this but It doesn't have downloads Option like cloudstream
> 
> @RowdyRogue Thank you for the feedback! I'm currently exploring options to get direct stream links in .mp4 or .m3u8 format, once I get a reliable source we'll ditch webview and downloading option will be available.

@BeamlakAschalew thank u dude  im looking forward to it

**Comment by BeamlakAschalew** [comment]
> > 13. It will be lot better if movies and series are displayed in grid style instead of list style when we click on genres.
> 
> I agree with this. Or maybe even a toggle for list/grid view in settings or somewhere else.

I will add an option to toggle between them, thanks for the suggestion!
