### ISSUE TITLE
Add new streaming services like these 

### ISSUE THREAD

**Issue by Fuzzythegoatq** [BeamlakAschalew/cinemax#50]
![Screenshot_20230817_010312_Plex](https://github.com/BeamlakAschalew/cinemax/assets/124460008/e1f3d253-b303-4911-815d-7895178501ec)
![Screenshot_20230817_010403_Plex](https://github.com/BeamlakAschalew/cinemax/assets/124460008/29c1eaad-b963-428d-b07a-191706ae2430)
![Screenshot_20230817_010417_Plex](https://github.com/BeamlakAschalew/cinemax/assets/124460008/5322e099-a817-42b4-8a80-8f355a8436dd)

I would really like if you could add these if you can't add wwe can you atleast add Google play movies and tubi?

**Comment by BeamlakAschalew** [comment]
I'm not getting this. What special thing do they provide that isn't already available?
