### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by Fuzzythegoatq** [BeamlakAschalew/cinemax#52]
### Steps to reproduce

I was just trying to use Cinemax when the app suddenly crashed and I double checked to make sure I ain't bugging and it crashed again

### Expected behavior

Go on the app to watch movies

### Actual behavior

Going on the app and it suddenly crashed

### Android version

Android 12

### Other details

And there is A LOT of stuff that needs to be added on this app if the app had the proper features it would revival cloud stream or it could be better then cloud stream but it would need way more sources for that to happen fully

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by BeamlakAschalew** [comment]
> ### Steps to reproduce
> 
> I was just trying to use Cinemax when the app suddenly crashed and I double checked to make sure I ain't bugging and it crashed again
> 
> ### Expected behavior
> 
> Go on the app to watch movies
> 
> ### Actual behavior
> 
> Going on the app and it suddenly crashed
> 
> ### Android version
> 
> Android 12
> 
> ### Other details
> 
> And there is A LOT of stuff that needs to be added on this app if the app had the proper features it would revival cloud stream or it could be better then cloud stream but it would need way more sources for that to happen fully
> 
> ### Acknowledgements
> 
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> - [X] I have written a short but informative title.
> - [X] I will fill out all of the requested information in this form.

Did this happen as soon as you opened the app?

**Comment by Fuzzythegoatq** [comment]
> 

Yes

**Comment by BeamlakAschalew** [comment]
> > 
> 
> Yes

It would be great if you provided me app version and the RAM of your device

**Comment by Fuzzythegoatq** [comment]
> > > 
> > 
> > 
> > Yes
> 
> It would be great if you provided me app version and the RAM of your device

I'm using the latest app version

**Comment by Fuzzythegoatq** [comment]
> > > 
> > 
> > 
> > Yes
> 
> It would be great if you provided me app version and the RAM of your device

Sorry for the late reply my ram usage is only 80M for the app and I'm using the latest version

**Comment by BeamlakAschalew** [comment]
> > > > 
> > > 
> > > 
> > > Yes
> > 
> > It would be great if you provided me app version and the RAM of your device
> 
> Sorry for the late reply my ram usage is only 80M for the app and I'm using the latest version 

No problem. This is weird behaviour from the app, I'll try it on different devices and I'll let you know

**Comment by Fuzzythegoatq** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Yes
> > > 
> > > 
> > > It would be great if you provided me app version and the RAM of your device
> > 
> > 
> > Sorry for the late reply my ram usage is only 80M for the app and I'm using the latest version
> 
> No problem. This is weird behaviour from the app, I'll try it on different devices and I'll let you know

Okay

**Comment by BeamlakAschalew** [comment]
Closed. Couldn't find any instance where the app crashes, re-open if it is still crashing.
